language: ruby
cache: bundler
rvm:
  - 2.7.1
  - 2.6
  - 2.5
  - 2.4
sudo: false
script: bundle exec rspec
services:
  - redis-server

before_install:
  - gem update --system
  # Update bundler to the latest
  - gem install bundler
